name: Deploy Ale Test Web Server STAGING

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUP3XHP2A5BNLTBHB
          aws-secret-access-key: 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
          aws-region: eu-central-1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: |
          chmod +x /home/ubuntu/update-test.sh  # Betik dosyasına çalıştırma izni ver
          /home/ubuntu/update-test.sh