# This is a basic workflow that is manually triggered

name: Manual workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  greet:

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUP3XHP2A5BNLTBHB
          aws-secret-access-key: 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
          aws-region: eu-central-1

      - name: Generate deployment package
        run: |
          sudo su
          cd /var/www/ale-test
          mkdir srdtest