name: Manual workflow

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  greet:
    runs-on: self-hosted

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUP3XHP2A62VQBRUN
          aws-secret-access-key: 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
          aws-region: eu-central-1

      - name: Create Database
        run: |
          
          mkdir -p /home/ubuntu/xxx
          touch /home/ubuntu/xxx/database.txt