name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUP3XHP2A5BNLTBHB
          aws-secret-access-key: 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
          aws-region: eu-central-1

      # Runs a single command using the runners shell
      - name: Send aaaaaa
        uses: actions/checkout@v2
        with:
          source: "."
          target: "/var/www/ale-test/update.sh"
          script: |
            cd -p var/www/ale-test
            git checkout .
            git pull
            mkdir abc
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Checkout
#        run: |
#          -p /var/www/ale-test/update.sh