name: Run Update Test Script

on:
  workflow_dispatch:  # Manuel tetikleme
  push:
    branches:
      - main  # veya kullanmak istediğiniz ana dal

jobs:
  run-update-test:
    runs-on: ubuntu-latest

    steps:
      - - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: AKIAUP3XHP2A62VQBRUN
            aws-secret-access-key: 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
            aws-region: eu-central-1

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Update Test Script
        run: |
          chmod +x /home/ubuntu/update-test.sh  # Betik dosyasına çalıştırma izni ver
          /home/ubuntu/update-test.sh